### ISSUE TITLE
FHIR profile of the bundle

### ISSUE THREAD

**Issue by hoffmka** [uniklinik-koeln-fhir/nngm-form-r4#1]
The FHIR profile of the bundle is missing.

**Comment by harry-preiss-medicalsyn** [comment]
Bundle (type "document") profile was added

**Comment by hoffmka** [comment]
I think at least the identifier needs to be more specified.
![image](https://user-images.githubusercontent.com/48366409/196156292-fc998474-1af5-47be-8361-b4af20b083ae.png)
