### ISSUE TITLE
Fixed value of element consent.status is "draft"

### ISSUE THREAD

**Issue by hoffmka** [uniklinik-koeln-fhir/nngm-form-r4#2]
In the profiles http://uk-koeln.de/fhir/StructureDefinition/nNGM/Consent and http://uk-koeln.de/fhir/StructureDefinition/nNGM/Consent the element status has the fixed value "draft" instead "active".

**Comment by harry-preiss-medicalsyn** [comment]
status changed to "active"

**Comment by hoffmka** [comment]
Did you forget to push the changes to the repository?
