### ISSUE TITLE
Code 'BUN' from system 'http://uk-koeln.de/fhir/CodeSystem/nNGM/identifier-type' does not exist in valueset 'http://uk-koeln.de/fhir/ValueSet/nNGM/IdentifierType'

### ISSUE THREAD

**Issue by hoffmka** [uniklinik-koeln-fhir/nngm-form-r4#6]
The element **Bundle.identifier.type.coding.code** is defined as **Fixed value** with content **'BUN'**, see https://simplifier.net/nngm-form/profile_nngm_bundle.
But the code 'BUN' doesn't exist in the valueset https://simplifier.net/nngm-form/CodeSystem-nNGM-Identifier-Type.
A validation error occurs.

Another question arises for me, wether the identifier is relevant or not. The "Brückenkopf" does not need this value. Is it relevant to the eCRF?

**Comment by harry-preiss-medicalsyn** [comment]
The ValueSet was updated in the GIT repository, but the reimport in simplifier was missing.
ValueSet is now up-to-date.
